- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Azure subscription 1(1)(39871908-78ed-4ef9-adbf-cb5c701334e3)'
    ScriptType: 'FilePath'
    ScriptPath: '''https://raw.githubusercontent.com/de8899/azure/master/deploy.ps1'''
    errorActionPreference: 'silentlyContinue'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Azure subscription 1(39871908-78ed-4ef9-adbf-cb5c701334e3)'
    ScriptType: 'FilePath'
    ScriptPath: 'https://raw.githubusercontent.com/de8899/azure/master/deploy.ps1'
    errorActionPreference: 'silentlyContinue'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true