pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@3
  inputs:
    azureSubscription: 'demo-deploy-sp'
    ScriptPath: 'https://raw.githubusercontent.com/de8899/azure/master/deploy.ps1'
    ScriptArguments: -ResourceGroupName 'RG1' -ResourceGroupLocation 'centralus'
    azurePowerShellVersion: LatestVersion